### ISSUE TITLE
adding hit info to JBrowse tracks

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/sequenceserver#6]
as discussed, some users have requested that we enable this functionality. It's possible that we could handle it via the genomic region linkout mechanism but I'm thinking about some aspects that might make it better done separately (and in any case using linkouts within the sequenceserver context is a work in progress). 

The basic mechanism sequenceserver provides for putting links into its results pages is described here:
https://sequenceserver.com/doc/#plugin
and here's [an example ](https://github.com/legumeinfo/sequenceserver/blob/bb5e4ef755776e8eab9bd9c7db7bfae4e14e61b6/lib/sequenceserver/links.rb#L63) of how we have used it in our instances previously.

The earlier JBrowse mechanism for adding hits is described [here](https://jbrowse.org/docs/faq.html#how-can-i-link-blast-results-to-jbrowse) explicitly with reference to sequenceserver; details in JBrowse2 have changed but that might still be of some use in thinking about how sequenceserver data can be processed for links. The JBrowse2 method is described [here](https://jbrowse.org/jb2/docs/urlparams/#sessiontracks) (note that we do not need to name BLAST hits "Boris").

One detail I am unclear about is whether it's possible to link all BLAST HSPs together as a combined feature; in gff this is sometimes done by setting the ID of grouped features to be the same, which might imply that giving "uniqueId" the same value in this context would work, but it may be that "uniqueness" here is different from the gff context, so that's just something to explore. In any case, having all HSPs represented rather than just a single feature representing min and max coordinates would probably be ideal.

@svengato I have put this under the legumeinfo sequenceserver but it applies to peanutbase as well (that repo is a fork of this one and doesn't seem to have issues enabled and we'll eventually want it for all LIS genera sequenceserver instances so best to track it here). Let me know if you run into any stumbling blocks such as getting a dev instance up and running for sequence server. Should be no harm in just pointing to an existing JBrowse2 instance as the target.

**Comment by adf-ncgr** [comment]
PS. for 
`    "assemblyNames": ["volvox"],
`
you can grab the id for the assembly from the yuckified prefixes on the genomic reference sequences that are the targets of the searches.

**Comment by svengato** [comment]
I see how to get SequenceServer hits into JBrowse, here is a contrived example in my local ZZBrowse-replacement version: (you said they need not be named "Boris")

<img width="700" alt="jbrowse-seqsrv-track" src="https://user-images.githubusercontent.com/8918336/229666148-e6b9cfb3-b113-4db2-8f80-dce550800c31.png">

but what action in SequenceServer should generate the JBrowse view in the first place? Do we need to add a new link that goes to a JBrowse instance with a track that displays the hits, similar to the example above but color-coded by score?

**Comment by adf-ncgr** [comment]
yes, the initial idea is to just use the[ mechanism](https://sequenceserver.com/doc/#plugin) that sequence server provides for adding links to its pages. The example I provided above where we provide a link to the legfed genomic linkout service page ought to be fairly similar to what would be needed here, at least as a first iteration

**Comment by adf-ncgr** [comment]
PS. although the hits need not be named Boris, please ensure they are full of washing-up liquid if you are going to try coloring by score (a nice-to-have, but not essential for now)

**Comment by svengato** [comment]
> yes, the initial idea is to just use the[ mechanism](https://sequenceserver.com/doc/#plugin) that sequence server provides for adding links to its pages.

That works, using fake data so far. Next: use real data as input.

<img width="535" alt="jbrowse-link-in-sequenceserver" src="https://user-images.githubusercontent.com/8918336/229893626-0df4313c-0a97-4930-ae92-388ef996bc94.png">

**Comment by adf-ncgr** [comment]
Note that this will probably only work when the targets are genomes, not proteins/transcripts (as in your example). I don't think there will be any way to get the genomic coordinates of the matched gene-derived entities (at least not without doing more work).

**Comment by svengato** [comment]
Right, I am trying to figure out which data are available.

**Comment by adf-ncgr** [comment]
The "LIS region linkouts" example I referenced earlier will probably give most of what's needed.

**Comment by svengato** [comment]
I am not finding any genomic regions for peanut, only genes. Do you have a specific query in mind?

**Comment by adf-ncgr** [comment]
You need to choose a genome as the db target, like "Arachis hypogaea Tifrunner v2 genome". If you commented all genomes out when trying to get the container built, you will need to retrace your steps.

**Comment by svengato** [comment]
No, the genomes are in there. I will try different sequence input.

<img width="971" alt="dbs" src="https://user-images.githubusercontent.com/8918336/229935077-7f52e13f-dc58-4437-8623-3f648a0c1711.png">

**Comment by adf-ncgr** [comment]
if you have something that matches a gene it likely will match the genome from which the gene is derived. I may need more context to understand what's happening.

**Comment by svengato** [comment]
I got it to return genomic regions, which are all entire chromosomes or scaffolds (does that seem correct?). Individual HSPs within each region are labeled (a, b, ..., z, aa, ab, ..., az, ba, bb, ...).

<img width="818" alt="hits" src="https://user-images.githubusercontent.com/8918336/229942555-3171eedb-d86a-431f-97bb-1a0aab6a3a19.png">

The query was two soybean sequences I used in Funnotate tests, compared to the A. hypogaea Tifrunner v2 genome. This may not be the best example, but let me know whether it seems on the right track.

Next:
- Pass extra information (HSP scores, etc) to JBrowse.
- Try it with a different JBrowse instance, like the one on the PeanutBase Jekyll site.

**Comment by adf-ncgr** [comment]
probably on right track, but a little hard to say with the anonymized HSP naming. I'd recommend naming them based on the query seq; the range on the query seq could be added as well, but might make it a bit "busy". If the names need to be unique, you can just add suffixes based on the rank of the HSP for now. If you get the code somewhere I can test it I may be able to give better direction.

**Comment by svengato** [comment]
That should be doable, in fact it is easy to get the other HSP attributes into JBrowse. They appear to be ordered by increasing "E value".

**Comment by svengato** [comment]
Something more like this?

<img width="475" alt="hits2" src="https://user-images.githubusercontent.com/8918336/229947844-b55128c3-f6fd-49ba-99a4-274610601e8e.png">

**Comment by adf-ncgr** [comment]
not quite. If the input fasta is:
```
>my_sequence
text of sequence follows
```
then the HSPs would be labeled as my_sequence-1 my_sequence-2, etc. although my_sequence (start-end) would probably also be fine.

**Comment by svengato** [comment]
If I understand correctly, all HSPs sent (per link) to JBrowse are associated with the same sequence, so the sequence name could go in the sessionTracks refName field (along with the full chromosome name).

**Comment by adf-ncgr** [comment]
You are probably right, however in an ideal world we might be able to figure out how to send data for multiple queries to the same track. I would guess that sessionTracks refName needs to specify the reference sequence id for the browser, so probably not a good idea to try to add in other stuff there. I suppose that other attributes can be added to the features other than the ones they explicit list in their JSON. But I still think labeling the features with the query sequence name as a base is probably going to be soothing to angsty users.

**Comment by svengato** [comment]
We should discuss it, when is a good time for a videoconference?

**Comment by svengato** [comment]
BLAST tutorial
https://www.ncbi.nlm.nih.gov/BLAST/tutorial/

**Comment by adf-ncgr** [comment]
sorry, I was a bit tied up earlier; did you still want to discuss by zoom?

**Comment by svengato** [comment]
Sure, any time

**Comment by adf-ncgr** [comment]
OK, I'll sprout one momentarily and send you a link

**Comment by svengato** [comment]
After some generalization, it works with the PeanutBase JBrowse.

**Comment by adf-ncgr** [comment]
great, maybe you can daemo it tomorrow's PB meeting and we can discuss how to roll it out properly (without skipping bits).

**Comment by svengato** [comment]
D&aelig;mo postponed to Monday.

**Comment by svengato** [comment]
Steven Cannon updated the peanut genome & annotations yesterday, changing the chromosome names. This broke my d&aelig;mo (and probably ZZBrowse eventually) because JBrowse still uses the old version. Please advise.

>   - 2023-04-06 sbc: replace genome_main with version prepared by ds_souschef. 
>       Change chromosome names from e.g. arahy.Tifrunner.gnm2.Arahy.01 to arahy.Tifrunner.gnm2.chr01

**Comment by adf-ncgr** [comment]
Since JBrowse is served directly from the datastore, I think the thing needed is probably to get the blast db updated. I can update the one hosted on the VMs, but if your dæmo is running locally I guess just delete the blast db that's currently there and rebuild it (should pull it down from the datastore)

**Comment by svengato** [comment]
That is how I noticed it, I had rebuilt the BLAST db in SequenceServer but not in my local JBrowse (or the PeanutBase one, of course). I can do it for the former if you do it for the latter. Thanks -

**Comment by adf-ncgr** [comment]
I'm not sure I follow- if the JBrowse is configured to read the genome from the datastore it should basically get the change automatically (possibly requiring a refresh or new session to be initiated)

**Comment by svengato** [comment]
It is not updating for some reason, I still see peanut chromosomes as "Arahy.01". I will look into this.

**Comment by svengato** [comment]
There are indeed some build errors.

**Comment by adf-ncgr** [comment]
did you remember  export DOCKER_DEFAULT_PLATFORM=linux/amd64 if this is on your Mac?

**Comment by svengato** [comment]
That is for SequenceServer, which is working as expected ("chr01"). This is on the JBrowse end.

**Comment by adf-ncgr** [comment]
why do you need to build JBrowse?

**Comment by svengato** [comment]
Problem solved (I think) - I had changed the JBrowse configuration file and messed up a couple of lines.

**Comment by svengato** [comment]
Anyway, let me know when the PeanutBase JBrowse is up to speed. Steven also added a new peanut annotation file which contains the new chromosome name format,

https://data.legumeinfo.org/Arachis/hypogaea/annotations/Tifrunner.gnm2.ann2.PVFB/arahy.Tifrunner.gnm2.ann2.PVFB.gene_models_main.gff3.gz

**Comment by adf-ncgr** [comment]
as far as I know the PeanutBase JBrowse is up to speed:
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/2009605/230687264-2c26a56c-eb7f-4cdf-92ac-02eb45533f7d.png">
although I guess it hasn't been updated to have the newer gene annotations yet

**Comment by svengato** [comment]
I added the new annotation to the config.json on dev-pb-jekyll, but it does not appear. Does the existing arahy.Tifrunner.gnm2 assembly line in the old annotation (.ann1.4K0L) need renaming?

**Comment by adf-ncgr** [comment]
you may be getting confused by the fact that we switched https://dev.peanutbase.org/tools/jbrowse2/ to proxy the shared JBrowse that we have set up on the hardy VM jbrowse2-legumeinfo instead of the one that was earlier installed locally on the dev-pb-jekyll VM. Sorry about that. I've added the gnm2.ann2 to the hardy instance which seems to display it now, but the older one (gnm2.ann1) is broken, presumably because chromosome names await being updated there.

**Comment by svengato** [comment]
I see it now, though there are two "Arachis hypogaea Tifrunner Annotations ..." tracks and (for now) the user has to know to select the lower one.

**Comment by adf-ncgr** [comment]
Yes, I agree that is an issue that needs to get resolved about the way the autocontent tool formulates the display names. I'll file one over there

**Comment by adf-ncgr** [comment]
For hits to the negative strand, the coordinates reported in the BLAST results will have start > end. This needs to be reversed to be interpretable by JBrowse which assumes start <= end. For example try following the JBrowse link for https://dev.peanutbase.org/tools/sequenceserver/679021e9-832b-4dcb-a183-a91160f7c7db

**Comment by adf-ncgr** [comment]
Another problem seems to appear when the reported e-value for a hit is 0, there's an error message on the JBrowse end about an exponent missing a number; as seen with 
https://dev.peanutbase.org/tools/sequenceserver/d98ad760-55d1-436f-9517-8919f57681d8
presumably removing the e-values would be one way of handling it, but I suspect it's a formatting issue on the part of the code formulating the link contents

**Comment by svengato** [comment]
Fixed (a) start < end, (b) do not convert evalue = 0 to scientific notation. See pull request #7.

**Comment by adf-ncgr** [comment]
looks good. I will try to do a little more testing and maybe we can discuss the pros/cons of the URI length vs having all the details on the HSPs in today's meeting before merging the PR.
